default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
        args:
          - --unsafe
      - id: check-json
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        types: [yaml]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.0
    hooks:
      - id: yamllint
        args: []
  # Note: for SQLFluff we don't use the default pre-commit hook because
  # the pre-commit managed python environment can be difficult to install,
  # especially due to issues with pyarrow being brought in by Snowflake.
  # This keep things more predictable by using the poetry.lock environment.
  - repo: local
    hooks:
      - id: sqlfluff
        name: sqlfluff
        language: system
        description: "Lints sql files with `SQLFluff`"
        types: [sql]
        require_serial: true
        entry: poetry run sqlfluff fix --show-lint-violations --processes 0 --nocolor --disable-progress-bar --force
        pass_filenames: true
