name: test

on:
  pull_request:
  push:
    branches:
      - main
permissions:
  contents: write

env:
  DBT_PROFILES_DIR: transform/ci
  SNOWFLAKE_PRIVATE_KEY: ${{ SECRETS.SNOWFLAKE_PRIVATE_KEY }}
  SNOWFLAKE_USER: ${{ SECRETS.SNOWFLAKE_USER }}
  SNOWFLAKE_ACCOUNT: ${{ SECRETS.SNOWFLAKE_ACCOUNT }}

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: caldata-infrastructure-template
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Setup git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: Install dependencies 
        run: |
          pipx install copier poetry
      - name: Test template
        run: ./caldata-infrastructure-template/ci/test.sh
